### ISSUE TITLE
invalid parameters list

### ISSUE THREAD

**Issue by Manuiq** [mamantoha/lifecell_api#1]
When running the example project there is an error(seems that the api has changed its structure):

> life.sign_in
> Life::MethodError: INVALID_PARAMETERS_LIST
>     from /Library/Ruby/Gems/2.0.0/gems/life-api-0.1.5/lib/life-api.rb:124:in `request'
>     from /Library/Ruby/Gems/2.0.0/gems/life-api-0.1.5/lib/life-api/methods.rb:32:in`sign_in'
>     from (irb):4
>     from /usr/bin/irb:12:in `<main>'

**Comment by mamantoha** [comment]
This is normal. You must provide `msisdn` and `password` to access the API.

**Comment by Manuiq** [comment]
Thanks for help, it turns out the problem was in <code>msisdn</code> number format - it should not contain the "+" sign like stated in this sentence:
"Authentication with password to the life:) API is accomplished using a phone number(msisdn) starting with a plus sign ("+") and the country code("380")"
