### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by bodqhrohro** [mamantoha/lifecell_api#2]
The certificate was changed and now it doesn't cover the api.life.com.ua domain, though the endpoints still seem to work.

Could you please pass `ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE`, or update `api_url` (possibly it migrated to a lifecell.ua subdomain long ago?), or so?

**Comment by mamantoha** [comment]
Hi @bodqhrohro . Thank you for the update. The correct URL is now fixed to https://api.lifecell.com.ua/ in version 0.6.0.
